// Runs the Sprint 2 demonstration against the local API and writes docs/EVIDENCE_OUTPUT.md
// Usage: npm run dev (terminal 1)  ->  npm run evidence (terminal 2)
import dotenv from 'dotenv';
import { writeFileSync } from 'node:fs';
dotenv.config({ path: '.env.local' });
dotenv.config();

const BASE = process.env.TEST_BASE_URL || 'http://localhost:3000';
const uid = Date.now().toString(36);
const out = ['# Sprint 2 evidence (generated by scripts/evidence.mjs)', '', `Base URL: ${BASE}`, 'Token and Supabase project URL are redacted.', ''];
let token;
let n = 0;

async function call(title, method, path, body, useToken = true) {
  n += 1;
  const res = await fetch(`${BASE}/api/v1/admin${path}`, {
    method,
    headers: { 'Content-Type': 'application/json', ...(useToken && token ? { Authorization: `Bearer ${token}` } : {}) },
    body: body ? JSON.stringify(body) : undefined
  });
  const json = await res.json().catch(() => ({}));
  out.push(`## ${n}. ${title}`, '', '```http', `${method} /api/v1/admin${path}`, useToken ? 'Authorization: Bearer <REDACTED>' : '(no Authorization header)', 'Content-Type: application/json', body ? `\n${JSON.stringify(body, null, 2)}` : '', '```', '', `Response: **${res.status}**`, '', '```json', JSON.stringify(json, null, 2), '```', '');
  console.log(`${n}. ${title} -> ${res.status}`);
  return { status: res.status, json };
}

const login = await fetch(`${process.env.SUPABASE_URL}/auth/v1/token?grant_type=password`, {
  method: 'POST',
  headers: { apikey: process.env.SUPABASE_ANON_KEY, 'Content-Type': 'application/json' },
  body: JSON.stringify({ email: process.env.TEST_ADMIN_EMAIL, password: process.env.TEST_ADMIN_PASSWORD })
});
token = (await login.json()).access_token;
if (!token) { console.error('Login failed. Check TEST_ADMIN_EMAIL / TEST_ADMIN_PASSWORD / SUPABASE_URL / SUPABASE_ANON_KEY in .env.local'); process.exit(1); }

const parent = await call('Create parent category', 'POST', '/categories', { name: 'Demo Face', slug: `demo-face-${uid}` });
const child = await call('Create child category', 'POST', '/categories', { name: 'Demo Lips', slug: `demo-lips-${uid}`, parent_id: parent.json.data?.id });
const prod = await call('Create draft product', 'POST', '/products', { name: 'Demo Lipstick', slug: `demo-lipstick-${uid}`, description: 'Demo product', category_id: child.json.data?.id });
const pid = prod.json.data?.id;
const variant = await call('Create variant', 'POST', `/products/${pid}/variants`, { option_values: { shade: 'Demo Rose' } });
const sku = await call('Create SKU', 'POST', `/products/${pid}/skus`, { variant_id: variant.json.data?.id, sku_code: `DEMO-ROSE-${uid}`, price: 799.0, stock_quantity: 10 });
await call('Update SKU price and stock', 'PATCH', `/skus/${sku.json.data?.id}`, { price: 850.5, stock_quantity: 12 });
await call('Publish product (has sellable SKU)', 'PATCH', `/products/${pid}`, { status: 'published' });
await call('List products', 'GET', '/products');
await call('List categories', 'GET', '/categories');

out.push('# Rejection cases', '');
await call('No token -> 401', 'GET', '/products', null, false);
await call('Duplicate category slug -> 409', 'POST', '/categories', { name: 'Dup', slug: `demo-face-${uid}` });
await call('Duplicate SKU code -> 409', 'POST', `/products/${pid}/skus`, { variant_id: variant.json.data?.id, sku_code: `DEMO-ROSE-${uid}`, price: 1, stock_quantity: 1 });
await call('Negative stock -> 400', 'PATCH', `/skus/${sku.json.data?.id}`, { stock_quantity: -5 });
await call('Category cycle -> 400', 'PATCH', `/categories/${parent.json.data?.id}`, { parent_id: child.json.data?.id });

writeFileSync('docs/EVIDENCE_OUTPUT.md', out.join('\n'));
console.log('\nSaved docs/EVIDENCE_OUTPUT.md');
