-- Blushique / Sprint 2 catalog foundation
create extension if not exists pgcrypto;

do $$
begin
  create type public.user_role as enum ('customer', 'admin');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.product_status as enum ('draft', 'published');
exception when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.user_role not null default 'customer',
  full_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.categories(id) on delete restrict on update cascade,
  name text not null,
  slug text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete restrict on update cascade,
  name text not null,
  slug text not null unique,
  description text,
  status public.product_status not null default 'draft',
  specifications jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_specifications_object check (jsonb_typeof(specifications) = 'object')
);

create table if not exists public.variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade on update cascade,
  option_values jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint variants_option_values_object check (jsonb_typeof(option_values) = 'object'),
  constraint variants_has_option check (jsonb_object_length(option_values) > 0)
);

create unique index if not exists variants_product_options_uq on public.variants(product_id, option_values);

create table if not exists public.skus (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade on update cascade,
  variant_id bigint not null references public.variants(id) on delete cascade on update cascade,
  sku_code text not null unique,
  price numeric(12,2) not null,
  stock_quantity integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint skus_price_nonnegative check (price >= 0),
  constraint skus_stock_nonnegative check (stock_quantity >= 0)
);

create index if not exists skus_product_idx on public.skus(product_id);
create index if not exists skus_variant_idx on public.skus(variant_id);

create table if not exists public.assets (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade on update cascade,
  variant_id bigint references public.variants(id) on delete cascade on update cascade,
  storage_key text not null,
  role text not null,
  alt_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  constraint assets_owner_check check ((product_id is not null) or (variant_id is not null)),
  constraint assets_sort_nonnegative check (sort_order >= 0)
);

-- Sprint 1 MVP entities retained so Sprint 2 remains traceable to the original ERD.
create table if not exists public.carts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade on update cascade,
  updated_at timestamptz not null default now(),
  unique(user_id)
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  cart_id bigint not null references public.carts(id) on delete cascade on update cascade,
  sku_id bigint not null references public.skus(id) on delete restrict on update cascade,
  quantity integer not null,
  constraint cart_items_quantity_positive check (quantity > 0),
  unique(cart_id, sku_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict on update cascade,
  total_amount numeric(12,2) not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  constraint orders_total_nonnegative check (total_amount >= 0)
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete restrict on update cascade,
  sku_id bigint not null references public.skus(id) on delete restrict on update cascade,
  quantity integer not null,
  unit_price numeric(12,2) not null,
  constraint order_items_quantity_positive check (quantity > 0),
  constraint order_items_price_nonnegative check (unit_price >= 0)
);

-- Prevent a variant from being paired with a SKU belonging to another product.
create or replace function public.validate_sku_product_variant()
returns trigger language plpgsql as $$
begin
  if not exists (select 1 from public.variants v where v.id = new.variant_id and v.product_id = new.product_id) then
    raise exception 'SKU variant must belong to the same product' using errcode = '23514';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_validate_sku_product_variant on public.skus;
create trigger trg_validate_sku_product_variant
before insert or update of product_id, variant_id on public.skus
for each row execute function public.validate_sku_product_variant();

-- Prevent category cycles (a category cannot become its own ancestor).
create or replace function public.prevent_category_cycle()
returns trigger language plpgsql as $$
declare
  current_id bigint;
begin
  if new.parent_id is null then return new; end if;
  if new.parent_id = new.id then raise exception 'Category cannot be its own parent' using errcode = '23514'; end if;
  current_id := new.parent_id;
  while current_id is not null loop
    if current_id = new.id then raise exception 'Category hierarchy cycle is not allowed' using errcode = '23514'; end if;
    select parent_id into current_id from public.categories where id = current_id;
  end loop;
  return new;
end;
$$;

drop trigger if exists trg_prevent_category_cycle on public.categories;
create trigger trg_prevent_category_cycle
before insert or update of parent_id on public.categories
for each row execute function public.prevent_category_cycle();

-- A published product must have at least one active, in-stock SKU (checked at commit).
create or replace function public.check_product_sellable(pid bigint)
returns void language plpgsql as $$
begin
  if exists (select 1 from public.products p where p.id = pid and p.status = 'published')
     and not exists (select 1 from public.skus s where s.product_id = pid and s.is_active = true and s.stock_quantity > 0) then
    raise exception 'Published product must have at least one sellable SKU' using errcode = '23514';
  end if;
end;
$$;

create or replace function public.trg_check_product_sellable()
returns trigger language plpgsql as $$
begin
  perform public.check_product_sellable(new.id);
  return new;
end;
$$;

create or replace function public.trg_check_sku_keeps_product_sellable()
returns trigger language plpgsql as $$
begin
  if tg_op = 'DELETE' then
    perform public.check_product_sellable(old.product_id);
    return old;
  end if;
  perform public.check_product_sellable(new.product_id);
  return new;
end;
$$;

drop trigger if exists trg_product_requires_sku on public.products;
create constraint trigger trg_product_requires_sku
after insert or update of status on public.products
deferrable initially deferred for each row execute function public.trg_check_product_sellable();

drop trigger if exists trg_sku_keeps_product_sellable on public.skus;
create constraint trigger trg_sku_keeps_product_sellable
after insert or update or delete on public.skus
deferrable initially deferred for each row execute function public.trg_check_sku_keeps_product_sellable();

-- Minimal updated_at trigger.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

do $$ declare t text; begin
  foreach t in array array['profiles','categories','products','variants','skus'] loop
    execute format('drop trigger if exists trg_%s_updated_at on public.%I', t, t);
    execute format('create trigger trg_%s_updated_at before update on public.%I for each row execute function public.set_updated_at()', t, t);
  end loop;
end $$;

-- RLS: clients cannot directly write catalog data. Admin API uses the service role only after JWT+role verification.
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.variants enable row level security;
alter table public.skus enable row level security;
alter table public.assets enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

-- Admin-only direct database policies; API remains the documented administration contract.
do $$ begin
  if not exists (select 1 from pg_policies where policyname='admins_manage_categories' and tablename='categories') then
    create policy admins_manage_categories on public.categories for all using (public.is_admin()) with check (public.is_admin());
  end if;
  if not exists (select 1 from pg_policies where policyname='admins_manage_products' and tablename='products') then
    create policy admins_manage_products on public.products for all using (public.is_admin()) with check (public.is_admin());
  end if;
  if not exists (select 1 from pg_policies where policyname='admins_manage_variants' and tablename='variants') then
    create policy admins_manage_variants on public.variants for all using (public.is_admin()) with check (public.is_admin());
  end if;
  if not exists (select 1 from pg_policies where policyname='admins_manage_skus' and tablename='skus') then
    create policy admins_manage_skus on public.skus for all using (public.is_admin()) with check (public.is_admin());
  end if;
end $$;
